site_name: Lima Smart PRD
site_url: https://example.com/
nav:
    - Home: index.md
markdown_extensions:
  - attr_list
theme:
    nav_style: dark
    name: material
    palette:
      primary: green
    font:
      text: Roboto Mono


